services:
  apache:
    build: .
    container_name: resellers_project-apache
    ports:
      - '8083:80' # Mapea el puerto 80 del contenedor al puerto 8082 del host
    volumes:
      - ./resellers:/var/www/html # Monta el directorio local ./resellers en /var/www/html en el contenedor
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: always # Reinicia el contenedor automáticamente
